# Build settings

port: 4000
markdown:  kramdown
permalink: /:title
plugins:   [jekyll-sitemap, jekyll-feed,  jekyll-seo-tag]
url: axeltan.com

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)

title:		   "Axel Tan"
description: "Aspiring Cloud/DevOps engineer"
