#-------------------------------
# General Site Settings

menu:
- {name: 'Projects', url: 'projects'}
- {name: 'About',    url: 'about'}
- {name: 'Contact',  url: 'contact'}

#-------------------------------
# Projects Section

projects:
- {name: 'Notion Automation', url: 'notion-automation'}

#-------------------------------
# Contact Section

social:
- {icon: 'github',    link: 'https://github.com/axeltanxl'}
- {icon: 'linkedin',  link: 'https://linkedin.com/in/axeltanxl'}
- {icon: 'envelope',  link: 'mailto:axeltan@outlook.sg'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: "Axel Tan's personal website"
  rel-author: 'https://plus.google.com/u/0/#'
  rel-publisher: 'https://plus.google.com/u/0/#'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-analytics-ua: 'UA-204950988-1'

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'axeltan'
